name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './webapp/package-lock.json'
      - name: Install dependencies
        run: |
          cd webapp
          npm ci
      - name: Build Angular App
        run: |
          cd webapp
          npm run build
      - name: Enhanced Debug - Verify all files
        run: |
          echo "Workspace contents:"
          ls -la
          
          echo "Checking webapp directory:"
          ls -la webapp
          
          echo "Checking if dist exists:"
          ls -la webapp/dist
          
          echo "Checking dist/webapp contents:"
          ls -la webapp/dist/webapp
          
          echo "Checking browser directory contents:"
          ls -la webapp/dist/webapp/browser
          
          echo "Checking specifically for index.html:"
          find . -name "index.html" | sort
      - name: Prepare Deployment
        run: |
          echo "Creating clean output directory:"
          rm -rf output_static_webapp
          mkdir -p output_static_webapp
          
          echo "Copying browser subdirectory contents to root of output directory:"
          cp -rv webapp/dist/webapp/browser/* output_static_webapp/
          
          echo "Copying any other required assets from original build:"
          if [ -d webapp/dist/webapp/assets ]; then
            cp -rv webapp/dist/webapp/assets output_static_webapp/
          fi
          
          echo "Verifying output_static_webapp contents after copy:"
          ls -la output_static_webapp/
          
          echo "Checking specifically for index.html in output directory:"
          if [ -f output_static_webapp/index.html ]; then
            echo "SUCCESS: index.html exists in output_static_webapp/"
            cat output_static_webapp/index.html | head -5
          else
            echo "ERROR: index.html still NOT found in output_static_webapp/"
            echo "Creating minimal index.html as fallback:"
            echo '<!DOCTYPE html><html><head><title>Test Page</title></head><body><h1>Hello World</h1></body></html>' > output_static_webapp/index.html
            ls -la output_static_webapp/
          fi
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GREEN_HILL_0F804F103 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "./output_static_webapp"
          api_location: ""
          output_location: ""
          skip_app_build: true

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GREEN_HILL_0F804F103 }}
          action: "close"
          app_location: "./webapp" 