name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Build Angular App
        run: |
          cd webapp
          npm ci
          npm run build
      - name: Check for large files
        run: |
          echo "Checking file sizes in the dist directory:"
          find webapp/dist -type f -size +5M | sort -k2 -n
          echo "Total size of dist directory:"
          du -sh webapp/dist
      - name: Prepare Deployment (Minimal)
        run: |
          mkdir -p output_static_webapp
          # Copy only the essential files
          cp webapp/dist/webapp/browser/index.html output_static_webapp/
          cp webapp/routes.json output_static_webapp/
          mkdir -p output_static_webapp/assets
          # Copy JS and CSS files
          find webapp/dist/webapp/browser -name "*.js" -o -name "*.css" | xargs -I{} cp {} output_static_webapp/
          # Check size of deployment package
          echo "Size of deployment directory:"
          du -sh output_static_webapp
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GREEN_HILL_0F804F103 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "./output_static_webapp"
          api_location: ""
          output_location: ""
          skip_app_build: true

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GREEN_HILL_0F804F103 }}
          action: "close"
          app_location: "./webapp"
