name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Build Angular App
        run: |
          cd webapp
          npm ci
          npm run build
      - name: Check for large files
        run: |
          echo "Checking file sizes in the dist directory:"
          find webapp/dist -type f -size +5M | sort -k2 -n
          echo "Total size of dist directory:"
          du -sh webapp/dist
      - name: Prepare Deployment (Including Icons and Critical Assets)
        run: |
          mkdir -p output_static_webapp
          # Copy index.html and routes.json
          cp webapp/dist/webapp/browser/index.html output_static_webapp/
          cp webapp/routes.json output_static_webapp/
          
          # Copy JS and CSS files
          find webapp/dist/webapp/browser -name "*.js" | xargs -I{} cp {} output_static_webapp/
          find webapp/dist/webapp/browser -name "*.css" | xargs -I{} cp {} output_static_webapp/
          
          # Copy favicon
          find webapp/dist/webapp/browser -name "favicon.ico" | xargs -I{} cp {} output_static_webapp/
          
          # Copy Bootstrap icons and media
          mkdir -p output_static_webapp/media
          if [ -d webapp/dist/webapp/browser/media ]; then
            cp -r webapp/dist/webapp/browser/media/* output_static_webapp/media/
          fi
          
          # Look for font files (.woff, .woff2, etc.) and copy them
          find webapp/dist/webapp/browser -name "*.woff" -o -name "*.woff2" -o -name "*.ttf" -o -name "*.eot" -o -name "*.svg" | xargs -I{} cp {} output_static_webapp/
          
          # Create assets directory if needed
          mkdir -p output_static_webapp/assets
          if [ -d webapp/dist/webapp/browser/assets ]; then
            cp -r webapp/dist/webapp/browser/assets/* output_static_webapp/assets/
          fi
          
          # Check size of deployment package
          echo "Size of deployment directory:"
          du -sh output_static_webapp
          echo "Content of output directory:"
          find output_static_webapp -type f | sort
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GREEN_HILL_0F804F103 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "./output_static_webapp"
          api_location: ""
          output_location: ""
          skip_app_build: true

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GREEN_HILL_0F804F103 }}
          action: "close"
          app_location: "./webapp" 