name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './webapp/package-lock.json'
      - name: Install dependencies
        run: |
          cd webapp
          npm ci
      - name: Build Angular App
        run: |
          cd webapp
          npm run build
      - name: Debug - Verify files
        run: |
          echo "Checking browser directory contents:"
          ls -la webapp/dist/webapp/browser
          
          echo "Checking for index.html and routes.json:"
          find webapp -name "index.html" -o -name "routes.json" | sort
          
          echo "Checking if routes.json was copied to build output:"
          if [ -f webapp/dist/webapp/browser/routes.json ]; then
            echo "routes.json exists in build output"
            cat webapp/dist/webapp/browser/routes.json | head -5
          else
            echo "WARNING: routes.json not found in build output"
          fi
      - name: Prepare Deployment
        run: |
          echo "Creating clean output directory:"
          rm -rf output_static_webapp
          mkdir -p output_static_webapp
          
          echo "Copying browser subdirectory contents to root of output directory:"
          cp -rv webapp/dist/webapp/browser/* output_static_webapp/
          
          echo "Removing any potential problematic files:"
          find output_static_webapp -name "*.br" -delete
          find output_static_webapp -name "*.gz" -delete
          
          echo "Verifying output_static_webapp contents:"
          ls -la output_static_webapp/
          
          echo "Checking for routes.json in output directory:"
          if [ -f output_static_webapp/routes.json ]; then
            echo "SUCCESS: routes.json exists in output_static_webapp/"
          else
            echo "WARNING: routes.json not found in output directory, copying from source"
            cp -v webapp/routes.json output_static_webapp/
          fi
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GREEN_HILL_0F804F103 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "./output_static_webapp"
          api_location: ""
          output_location: ""
          skip_app_build: true
          production_branch: "main"
          deployment_environment: "production"

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GREEN_HILL_0F804F103 }}
          action: "close"
          app_location: "./webapp"
